### ISSUE TITLE
Global Settings for the plugin can become inaccessible

### ISSUE THREAD

**Issue by taymossimc** [caiocarvalhofre/moodle-mod_maici#5]
@christiansteier:tchncs.de (on Matrix) sent me this message:
"Hi Tay, I'm afraid I haven't made much progress with my test due to issues setting up the plugin correctly. I tried to adjust the key but can no longer access the corresponding editing area. Would you like me to create a GitHub ticket for this?"
![MAICI](https://github.com/caiocarvalhofre/moodle-mod_maici/assets/110061778/5973a386-e0cc-4dc0-a7c6-81ea9b3e5fc8)

**Comment by nadavkav** [comment]
I fixed it locally by changing:
$settings = new admin_settingpage('mod_maici_settings', new lang_string('pluginname', 'mod_maici'));
to:
$settings = new admin_settingpage('modsettingmaici', new lang_string('pluginname', 'mod_maici'));

**Comment by caiocarvalhofre** [comment]
Hello, @nadavkav I fixed it by removing the line completely. It wasn't necessary.
