### ISSUE TITLE
New and deprecated language models

### ISSUE THREAD

**Issue by pidaback** [caiocarvalhofre/moodle-mod_maici#8]
OpenAI released [gpt-4o](https://openai.com/index/hello-gpt-4o). I added the necessary key/value-pairs in my local test system and it works flawlessly. However, when I edited the code, I realized some changes to the language models this plug-in offers might be useful:
- gpt-4o could be added.
- gpt-4-0314 should be removed as it does not work anymore.
- gpt-4-turbo could be added (Many users won’t be aware that gpt-4-1106-preview is also a gtp-4-turbo model).
- gpt-3.5-turbo-16k-0613 and gpt-3.5-turbo-0613 should be removed now or in the next few weeks as they will probably stop working [on June 13th](https://platform.openai.com/docs/models/gpt-3-5-turbo).

Two other models will probably be shut down rather sooner than later:
- gpt-3.5-turbo-16k has „legacy“ status.
- gpt-3.5-turbo-0301 [might be](https://platform.openai.com/docs/deprecations/2023-06-13-updated-chat-models) shut down on June 13th as well (but might also keep functioning for a few more months).

By the way, would you be interested in pull requests? I noticed some smaller issues that might be easy to fix (but hard to describe). I couldn’t promise you to deliver something as quickly as you always do, however!

**Comment by nadavkav** [comment]
Maybe add an option to input the name of the model? (in case it has similar API endpoints)

**Comment by taymossimc** [comment]
Pull requests, you bet! Pleaese do add.

**Comment by caiocarvalhofre** [comment]
Hi @pidaback we updated model list. Its in the last commit.
